name: Project deployment

on:
  push:
    branches:
      - develop
      - master

jobs:
  setup:
    name: Preparation
    outputs:
      branchName: ${{ steps.extract_branch.outputs.branchName }}
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get install sshpass
    - name: Extract branch name
      uses: bernardo-mg/extract-branch-name-action@v1
      id: extract_branch

  deploy_docs:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Build page
      run: npm run copy-all
    - name: Deploy development version
      if: ${{ 'develop' == inputs.branch }}
      run: |
        cd src
        sshpass -p ${{ secrets.DEPLOY_DOCS_PASSWORD }} scp -o 'StrictHostKeyChecking no' -P ${{ secrets.DEPLOY_DOCS_PORT }} -r ./* ${{ secrets.DEPLOY_DOCS_USERNAME }}'@'${{ secrets.DEPLOY_DOCS_HOST }}':'${{ secrets.DEPLOY_DOCS_PATH_DEVELOP }};
    - name: Deploy final version
      if: ${{ 'master' == inputs.branch }}
      run: |
        cd src
        sshpass -p ${{ secrets.DEPLOY_DOCS_PASSWORD }} scp -o 'StrictHostKeyChecking no' -P ${{ secrets.DEPLOY_DOCS_PORT }} -r ./* ${{ secrets.DEPLOY_DOCS_USERNAME }}'@'${{ secrets.DEPLOY_DOCS_HOST }}':'${{ secrets.DEPLOY_DOCS_PATH_RELEASE }};
