name: Doc deployment

on: [push, pull_request]

jobs:

  setup_docs:
    name: Doc deployment preparation
    outputs:
      branchName: ${{ steps.extract_branch.outputs.branchName }}
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get install sshpass
    - name: Extract branch name
      uses: bernardo-mg/extract-branch-name-action@v1
      id: extract_branch

  deploy_docs:
    name: Deploy docs
    environment: deployment_site
    needs: setup_docs
    runs-on: ubuntu-latest
    if: ${{ needs.setup_docs.outputs.branchName == 'master' }}
    steps:
    - name: Check-out
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build page
      run: npm run copy-all
    - name: Move to deployment folder
      run: cd src
    - name: Deploy docs
      run: sshpass -p ${{ secrets.DEPLOY_DOCS_PASSWORD }} scp -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-dss -P ${{ secrets.DEPLOY_DOCS_PORT }} -r ./* ${{ secrets.DEPLOY_DOCS_USER }}'@'${{ secrets.DEPLOY_DOCS_HOST }}':'${{ secrets.DEPLOY_DOCS_PATH }};

  deploy_develop_docs:
    name: Deploy development docs
    environment: deployment_site
    needs: setup_docs
    runs-on: ubuntu-latest
    if: ${{ needs.setup_docs.outputs.branchName == 'develop' }}
    steps:
    - name: Check-out
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build page
      run: npm run copy-all
    - name: Move to deployment folder
      run: cd src
    - name: Deploy docs
      run: sshpass -p ${{ secrets.DEPLOY_DOCS_DEVELOP_PASSWORD }} scp -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-dss -P ${{ secrets.DEPLOY_DOCS_PORT }} -r ./* ${{ secrets.DEPLOY_DOCS_DEVELOP_USER }}'@'${{ secrets.DEPLOY_DOCS_HOST }}':'${{ secrets.DEPLOY_DOCS_DEVELOP_PATH }};
